### PR TITLE
Updates RGUI && Fixes samples and moves to example directory

### PR DESCRIPTION
**Pull request by Dacode45**
Moves samples out of their own crate and into the example directory, fixes the ones that can be easily fixed.

drop.rs, rgui.rs, yaw_pitch_roll.rs need reworks to work with 5.0
- Should also freeze mouse position 
- Updates rgui but did not validate that it works.

### CODE REVIEW

**Comment by IoIxD** [comment]
I was actually gonna suggest that rgui be moved to a new crate. 
I'll review this PR though since it's already been done.

**Review by IoIxD — APPROVED** [review]

**Review by IoIxD — CHANGES_REQUESTED** [review]
Please fix the unit test errors.

**Comment by IoIxD** [comment]
Fixed it myself.

**Comment by ShivanshuKantPrasad** [comment]
`Specs.rs` and `Roguelike.rs` were removed from `samples` folder but were not moved to `examples/samples` folder.

**Pull request merged**
